$(document).ready(function(){
    $('#hidden').hide();
    $('#wrapper').hide();
    $('#wrapper').fadeIn(3500);
    $('#here').click(function(){
        $('#hidden').slideToggle();
    });
    $('span').mouseover(function(){
        $(this).css("color","orange");
    });
    $('span').mouseleave(function(){
        $(this).css("color","#333333");
    });
    $('#here').mouseover(function(){
        $(this).css("color","red");
    });
    $('#here').mouseleave(function(){
        $(this).css("color","#333333");
    });
    $('#text').mouseover(function(){
        $('#hidden').css("opacity","0.7");
        $('#head').css("opacity","0.7");
    });
    $('#text').mouseleave(function(){
        $('#hidden').css("opacity","");
        $('#head').css("opacity","1");
    });
    $('#hidden').mouseover(function(){
        $('#text').css("opacity","0.7");
        $('#head').css("opacity","0.7");
    });
    $('#hidden').mouseleave(function(){
        $('#text').css("opacity","");
        $('#head').css("opacity","1");
    });
    $('#head').mouseover(function(){
        $('#text').css("opacity","0.7");
        $('#hidden').css("opacity","0.7");
    });
    $('#head').mouseleave(function(){
        $('#hidden').css("opacity","");
        $('#text').css("opacity","1");
    });
});
